data_config:
  data:
    count_norm: true
    dataset: kang
    log1p: true
  datasplit:
    holdout_cells:
    - CD4T
    holdout_perts: []
    mode: iid
  name: kang_ho_CD4T
model_config:
  model:
    hidden_dim: 800
    latent_dim: 100
  name: vae
  training:
    alpha: 0.001
    batsize: 32
    dropout_rate: 0.2
    epochs: 20
    learning_rate: 0.001
