name: satija_ho_genes

data: 
  path: /orcd/archive/abugoot/001/Projects/dlesman/datasets/satija_IFNB_HVG_and_perturbed_genes_normed.h5ad
  cell_key: cell_type
  pert_key: gene
  control: NT

datasplit:
  test_size: 1000
  control_size: 1000
  training:
    #Random folds need to be implemented
    #TODO: More complex splits

    #Annoying part is if we have random splits how will we define the tasks? -
    holdout_perts: [IFNAR1, TYK2, STAT2, USP18, IRF9, JAK1]

  evals:

    #What if there was a random fold before

    #Targets on which we evaluate when we do the holdout, can be ALL
    #If these are also heldout then we are evaluating on unseen cell + unseen pert
    #Set the combinations to evaluate on, we can implement more complex commands later on
    evaluation_targets: [[A549, IFNAR1], [A549, TYK2], [A549, STAT2], [A549, USP18], [A549, IRF9], [A549, JAK1]]


  #holdout_cells: [xxx]
  
  #test_size: 0.2
  #Something like this later on, i.e. stratification
  #groupby: ['species', 'condition']

    
dataloader:
  batch_size: 128
  shuffle: true
