dataset: satija_IFNB_raw
evaluation_targets:
- - A549
  - SP110
- - A549
  - CRKL
- - A549
  - STAT1
- - A549
  - STAT2
- - A549
  - MYC
- - A549
  - NFE2L3
- - A549
  - HERC5
- - A549
  - IFNAR2
- - A549
  - ETS1
- - A549
  - DRAP1
- - BXPC3
  - SP110
- - BXPC3
  - CRKL
- - BXPC3
  - STAT1
- - BXPC3
  - STAT2
- - BXPC3
  - MYC
- - BXPC3
  - NFE2L3
- - BXPC3
  - HERC5
- - BXPC3
  - IFNAR2
- - BXPC3
  - ETS1
- - BXPC3
  - DRAP1
- - HAP1
  - SP110
- - HAP1
  - CRKL
- - HAP1
  - STAT1
- - HAP1
  - STAT2
- - HAP1
  - MYC
- - HAP1
  - NFE2L3
- - HAP1
  - HERC5
- - HAP1
  - IFNAR2
- - HAP1
  - ETS1
- - HAP1
  - DRAP1
- - HT29
  - SP110
- - HT29
  - CRKL
- - HT29
  - STAT1
- - HT29
  - STAT2
- - HT29
  - MYC
- - HT29
  - NFE2L3
- - HT29
  - HERC5
- - HT29
  - IFNAR2
- - HT29
  - ETS1
- - HT29
  - DRAP1
- - K562
  - SP110
- - K562
  - CRKL
- - K562
  - STAT1
- - K562
  - STAT2
- - K562
  - MYC
- - K562
  - NFE2L3
- - K562
  - HERC5
- - K562
  - IFNAR2
- - K562
  - ETS1
- - K562
  - DRAP1
- - MCF7
  - SP110
- - MCF7
  - CRKL
- - MCF7
  - STAT1
- - MCF7
  - STAT2
- - MCF7
  - MYC
- - MCF7
  - NFE2L3
- - MCF7
  - HERC5
- - MCF7
  - IFNAR2
- - MCF7
  - ETS1
- - MCF7
  - DRAP1
name: eval_4
