name: satija_ho_A549_basic

data: 
  path: /orcd/archive/abugoot/001/Projects/dlesman/datasets/Seurat_IFNB.h5ad
  apply_norm: True
  apply_log1p: True
  gene_var_key: gene
  cell_key: cell_type
  pert_key: gene
  control: NT

datasplit:
  #test_size: 150
  #control_size: 150
  training:
    #Random folds need to be implemented
    #TODO: More complex splits

    #Annoying part is if we have random splits how will we define the tasks? -
    holdout_cells: [A549]

  evals:

    #What if there was a random fold before

    #Targets on which we evaluate when we do the holdout, can be ALL
    #If these are also heldout then we are evaluating on unseen cell + unseen pert
    #Set the combinations to evaluate on, we can implement more complex commands later on
    evaluation_targets: [[A549, IFNAR2]]


  #holdout_cells: [xxx]
  
  #test_size: 0.2
  #Something like this later on, i.e. stratification
  #groupby: ['species', 'condition']

    
dataloader:
  batch_size: 128
  shuffle: true
