
name: satija_test_eval_A549_only
mode: ood
#Annoying part is if we have random splits how will we define the tasks? -
holdout_perts: ['IFNAR2', 'STAT2']
holdout_cells: ['BXPC3', 'HAP1', 'HT29', 'K562', 'MCF7']


