dataset: satija_IFNB_raw
evaluation_targets:
- - A549
  - STAT4
- - A549
  - SMARCA5
- - A549
  - IFNAR2
- - A549
  - BRD9
- - A549
  - USP18
- - A549
  - TYK2
- - A549
  - CRKL
- - A549
  - DTX3L
- - A549
  - SP100
- - A549
  - HERC5
name: eval_4_ss:ns-10:5
