
name: preprocess_with_cell_embedding
metric_space: XXXX #Should be one of the precomputed cell embeddings for the dataset

cell_embedding:
  type: local # Can be local or precomputed
  name: vae  #If Local this should be a valid model name from the models section of the config, if precomputed this should be the name of the precomputed cell embedding
  
  embedding_config:
    name: vae
    model:
      latent_dim: 100
      hidden_dim: 800

    training:
      dropout_rate: 0.2
      learning_rate: 0.001
      alpha: 0.001
      epochs: 30
      batsize: 32



pert_embedding: None
log1p: True 
count_norm: True
