datasplit_config:
  dataset: essential_gene_knockouts_raw
  holdout_cells: []
  holdout_perts:
  - CEBPZ
  - DDX3X
  - KRTAP4-7
  - HSPH1
  - ATL2
  - ANKRD17
  - PPA1
  - EEFSEC
  - PSMD6
  - ATR
  - BUB3
  - POU5F1B
  - NMT1
  - CDK2
  - ATP5ME
  - SRPRB
  - NAA10
  - RFT1
  - GPS2
  - SNRPE
  mode: ood
  name: split_1_ood_ss:ns-20:10
etl_config:
  count_norm: true
  log1p: true
  pert_embedding: BioBERT
eval_config:
  dataset: essential_gene_knockouts_raw
  evaluation_targets:
  - - k562
    - CEBPZ
  - - k562
    - DDX3X
  - - k562
    - KRTAP4-7
  - - k562
    - HSPH1
  - - k562
    - ATL2
  - - k562
    - ANKRD17
  - - k562
    - PPA1
  - - k562
    - EEFSEC
  - - k562
    - PSMD6
  - - k562
    - ATR
  - - k562
    - BUB3
  - - k562
    - POU5F1B
  - - k562
    - NMT1
  - - k562
    - CDK2
  - - k562
    - ATP5ME
  - - k562
    - SRPRB
  - - k562
    - NAA10
  - - k562
    - RFT1
  - - k562
    - GPS2
  - - k562
    - SNRPE
  name: eval_1_ood_ss:ns-20:10
local_cell_embedding_config: null
model_config:
  cell_dist_metric: l2
  mean_shift: false
  name: nearest-neighbor_pert_emb_substitute
  num_of_degs: 20
  pert_dist_metric: l2
  pvalcut: 0.05
