name: satija_across_genes

data:
  dataset: satija_IFNB_raw
  apply_norm: True
  apply_log1p: True
  var_names_key: gene
  cell_key: cell_type
  pert_key: gene
  control: NT

datasplit:
  
  mode: ood
  holdout_perts: [IFNAR2, TYK2, STAT2, IFNAR1]

  

  #holdout_cells: [xxx]
  
  #test_size: 0.2
  #Something like this later on, i.e. stratification
  #groupby: ['species', 'condition']

    
dataloader:
  batch_size: 128
  shuffle: true
