HVG: false
cell_embeddings: []
cell_key: celltype
control: non-targeting
count_normalized: false
description: Downloaded from scPerturb website
folder_path: /orcd/data/omarabu/001/neelroy/SrivatsanTrapnell2020
gene_embeddings: []
log1p_transformed: false
path: /orcd/data/omarabu/001/neelroy/SrivatsanTrapnell2020/SrivatsanTrapnell2020_sciplex2.h5ad
pert_embeddings: []
pert_key: perturbation
precomputed_DEGs: false
var_names_key: null
