HVG: false
cell_embeddings: []
cell_key: cell_type
control: non-targeting
count_normalized: false
description: Downloaded from scPerturb website
folder_path: /orcd/data/omarabu/001/neelroy/TianKampmann2021
gene_embeddings: []
log1p_transformed: false
path: /orcd/data/omarabu/001/neelroy/TianKampmann2021/TianKampmann2021_CRISPRi.h5ad
pert_embeddings: []
pert_key: gene
precomputed_DEGs: false
var_names_key: null
