HVG: false
cell_embeddings: []
cell_key: null
control: non-targeting
count_normalized: false
description: Downloaded from scPerturb website
folder_path: /orcd/archive/abugoot/001/Projects/neelroy/XieHon2017
gene_embeddings: []
log1p_transformed: false
path: /orcd/archive/abugoot/001/Projects/neelroy/XieHon2017/XieHon2017.h5ad
pert_embeddings: []
pert_key: gene
precomputed_DEGs: false
var_names_key: null
