HVG: false
cell_embeddings: []
cell_key: cell_type
control: non-targeting
count_normalized: false
description: Downloaded from scPerturb website
folder_path: /orcd/archive/abugoot/001/Projects/neelroy/ZhaoSims2021
gene_embeddings: []
log1p_transformed: false
path: /orcd/archive/abugoot/001/Projects/neelroy/ZhaoSims2021/ZhaoSims2021.h5ad
pert_embeddings: []
pert_key: gene
precomputed_DEGs: false
var_names_key: null
