#version: This can be any text_field

name: nearest-neighbor_pert_emb_substitute_pca
mean_shift: False
num_of_degs: 20
pvalcut: 0.05
cell_metric_space: PCA
n_pca_components: 128
pert_dist_metric: l2
cell_dist_metric: l2
